---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Victoria-Spencer
--- DateTime: 2026/6/3 14:08
--- 字符串参数专项测试
---

local strArg = ARGV[1]
if strArg == nil then
    return -1
end
return string.len(strArg)