---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Victoria-Spencer
--- DateTime: 2026/6/3 8:31
--- 数字参数专项测试
---

local numArg = tonumber(ARGV[1])
if numArg == nil then
    return -1
end
return numArg + 1