---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Victoria-Spencer
--- DateTime: 2026/6/3 15:07
--- 座位Bitmap初始化专用脚本（强制覆盖，无状态校验）
---

local start = tonumber(ARGV[1])
local endSeq = tonumber(ARGV[2])
local status = tonumber(ARGV[3])

local bitmap1 = KEYS[1]
local bitmap2 = KEYS[2]

-- 基础参数校验
if not start or not endSeq or not status then return 0 end
if start < 0 or endSeq < 0 or start >= endSeq then return 0 end

-- 状态映射
local t, f
if status == 0 then
    -- 预锁定 01
    t, f = 0, 1
elseif status == 1 then
    -- 正式锁定 10
    t, f = 1, 0
elseif status == 2 then
    -- 已支付 11
    t, f = 1, 1
elseif status == 3 then
    -- 释放 00
    t, f = 0, 0
else
    return 0
end

-- 强制覆盖设置区间所有位
for i = start, endSeq - 1 do
    redis.call('SETBIT', bitmap1, i, t)
    redis.call('SETBIT', bitmap2, i, f)
end

return 1