---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Victoria-Spencer
--- DateTime: 2026/4/15 13:26
---

-- KEYS[1] = 临时锁Bitmap Key (PREORDER)
-- KEYS[2] = 正式订单Bitmap Key (ORDER)
-- ARGV[1] = 开始站序 startSeq
-- ARGV[2] = 结束站序 endSeq
-- ARGV[3] = 订单类型 orderType (0=预订单/临时, 1=正式订单)

local start = tonumber(ARGV[1])
local endSeq = tonumber(ARGV[2])
local orderType = tonumber(ARGV[3])

-- 基础参数校验
if start == nil or endSeq == nil or orderType == nil then
    return 0
end
-- 站序不能为负数
if start < 0 or endSeq < 0 then
    return 0
end
-- 开始站序必须 < 结束站序
if start >= endSeq then
    return 0
end
-- 订单类型只能是0或1
if orderType ~= 0 and orderType ~= 1 then
    return 0
end


-- 1. 【原子检查】左闭右开 [start, endSeq)
for i = start, endSeq - 1 do
    local tempBit = redis.call('GETBIT', KEYS[1], i)
    local formalBit = redis.call('GETBIT', KEYS[2], i)
    if tempBit == 1 or formalBit == 1 then
        return 0
    end
end

-- 2. 【动态锁定】根据orderType选择锁定哪个Bitmap
local targetKey = ""
if orderType == 0 then
    -- 预订单 → 锁定临时Bitmap
    targetKey = KEYS[1]
else
    -- 正式订单 → 锁定正式Bitmap
    targetKey = KEYS[2]
end

-- 3. 原子标记占用
for i = start, endSeq - 1 do
    redis.call('SETBIT', targetKey, i, 1)
end

return 1