---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Victoria-Spencer
--- DateTime: 2026/4/15 13:26
--- 双位图组合 状态机原子脚本
---

-- KEYS[1] = 座位位图1 (平级位图A)
-- KEYS[2] = 座位位图2 (平级位图B)
-- ARGV[1] = 开始站序 startSeq
-- ARGV[2] = 结束站序 endSeq
-- ARGV[3] = 座位状态 status (0=预订单锁定, 1=正式订单锁定, 2=支付，3释放)

local start = tonumber(ARGV[1])
local endSeq = tonumber(ARGV[2])
local status = tonumber(ARGV[3])

local bitmap1 = KEYS[1]
local bitmap2 = KEYS[2]

-- 基础参数校验
if start == nil or endSeq == nil or status == nil then
    return 0
end
if start < 0 or endSeq < 0 or start >= endSeq then
    return 0
end
if status ~= 0 and status ~= 1 and status ~= 2 and status ~= 3 then
    return 0
end

-- 校验区间内所有位的组合状态是否符合预期
local function checkState(tExpected, fExpected)
    for i = start, endSeq - 1 do
        local t = tonumber(redis.call('GETBIT', bitmap1, i))
        local f = tonumber(redis.call('GETBIT', bitmap2, i))
        if t ~= tExpected or f ~= fExpected then
            return false
        end
    end
    return true
end

-- 批量设置区间内所有位的组合状态
local function setState(tTarget, fTarget)
    for i = start, endSeq - 1 do
        redis.call('SETBIT', bitmap1, i, tTarget)
        redis.call('SETBIT', bitmap2, i, fTarget)
    end
end

-- ==============================================
-- 状态映射规则
-- 00 = 空闲
-- 01 = 预订单锁定(status=0)
-- 10 = 正式订单锁定(status=1)
-- 11 = 已支付永久锁定(status=2)
-- 00 = 释放后空闲(status=3)
-- ==============================================

-- 1. 预订单锁定 status=0：必须从 空闲(00) → 01
if status == 0 then
    if checkState(0, 0) then
        setState(0, 1)
        return 1
    else
        return 0
    end

-- 2. 正式订单锁定 status=1：必须从 预锁定(01) → 10
elseif status == 1 then
    if checkState(0, 1) then
        setState(1, 0)
        return 1
    else
        return 0
    end

-- 3. 已支付 status=2：必须从 正式锁定(10) → 11（永久锁定）
elseif status == 2 then
    if checkState(1, 0) then
        setState(1, 1)
        return 1
    else
        return 0
    end

-- 4. 释放座位 status=3：直接重置为 空闲(00)
elseif status == 3 then
    setState(0, 0)
    return 1

-- 无效操作
else
    return 0
end