---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Victoria-Spencer
--- DateTime: 2026/6/1 20:47
--- 双位图 原子回滚脚本（锁座失败逆向流转）
---

-- KEYS[1] = 位图1 (正式订单位图)
-- KEYS[2] = 位图2 (预订单位图)
-- ARGV[1] = 开始站序 startSeq
-- ARGV[2] = 结束站序 endSeq
-- ARGV[3] = 回滚类型 rollbackType (0=预锁失败回滚01→00，1=转正失败回滚10→01)

local start = tonumber(ARGV[1])
local endSeq = tonumber(ARGV[2])
local rollbackType = tonumber(ARGV[3])

local bitmap1 = KEYS[1]
local bitmap2 = KEYS[2]

-- 参数校验
if start == nil or endSeq == nil or rollbackType == nil then return 0 end
if start < 0 or endSeq < 0 or start >= endSeq then return 0 end
if rollbackType ~= 0 and rollbackType ~= 1 then return 0 end

-- 校验区间内所有位的组合状态
local function checkState(tExpected, fExpected)
    for i = start, endSeq - 1 do
        local t = tonumber(redis.call('GETBIT', bitmap1, i))
        local f = tonumber(redis.call('GETBIT', bitmap2, i))
        if t ~= tExpected or f ~= fExpected then
            return false
        end
    end
    return true
end

-- 批量设置状态
local function setState(tTarget, fTarget)
    for i = start, endSeq - 1 do
        redis.call('SETBIT', bitmap1, i, tTarget)
        redis.call('SETBIT', bitmap2, i, fTarget)
    end
end

-- ==============================================
-- 回滚场景1：预锁失败 → 01 回退为 00
-- ==============================================
if rollbackType == 0 then
    if checkState(0, 1) then
        setState(0, 0)
        return 1
    end
    return 0

-- ==============================================
-- 回滚场景2：转正失败 → 10 回退为 01
-- ==============================================
elseif rollbackType == 1 then
    if checkState(1, 0) then
        setState(0, 1)
        return 1
    end
    return 0
end

return 0