server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    # nacos注册中心配置
    nacos:
      discovery:
        server-addr: 192.168.43.143:8848
        namespace: 1
        group: DEFAULT_GROUP
  profiles:
    active: dev  # 激活生产环境配置
  datasource:
    url: jdbc:mysql://${spring.db.host}/rs-user
    username: ${spring.db.username}
    password: ${spring.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 扫描 resources/mapper 目录下的所有 XML 文件
  configuration:
    map-underscore-to-camel-case: true  # 开启下划线转驼峰
# jwt令牌配置
jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFG
  expiration: 720000